# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Bhagavadgeetha' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  pod 'FBSDKCoreKit'	

  # Pods for Bhagavadgeetha

  target 'BhagavadgeethaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BhagavadgeethaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
